# Generated by Django 5.0.1 on 2025-05-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_contactmessage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why_Invest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('discripation', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': '15. Why_Invest',
            },
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='mobile_image',
        ),
    ]
