# Generated by Django 5.0.2 on 2025-09-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_about_us_web_image_welcometo_web_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='icone2',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='title2',
        ),
    ]
